### PR TITLE
Candy rewards

### PR DESCRIPTION
**Pull request by jepke**
## Describe why this should be changed or added
Because candy are now used as quest rewards

## Describe alternatives you've considered
Theres not an alternative

## Additional context
Add any other context here.

### CODE REVIEW

**Comment by ccev** [comment]
fine with me.

**Review by versx — APPROVED** [review]

**Comment by fosJoddie** [comment]
depending on the number of different reward numbers possible, (currently afaik only 3 is used) it could be better to just implement this as `<pokemon_id>.png` ? 

From memory there's been special research quests that gave all kinds of different candy amounts (like a during Magikarp CD to get people to 400 candy fast). If they started pushing those into similar "high candy" quests it would turn into a lot of images with just different amounts printed on them.. Idk.. I don't feel strongly either way here, just my 2 cents

**Comment by jepke** [comment]
> depending on the number of different reward numbers possible, (currently afaik only 3 is used) it could be better to just implement this as `<pokemon_id>.png` ?
> 
> From memory there's been special research quests that gave all kinds of different candy amounts (like a during Magikarp CD to get people to 400 candy fast). If they started pushing those into similar "high candy" quests it would turn into a lot of images with just different amounts printed on them.. Idk.. I don't feel strongly either way here, just my 2 cents

400x are likely not to be seen as quest rewards. `_a` will be for the icon repos that go the last mile `<pkmnid>.png` will be first fallback

**Comment by fosJoddie** [comment]
> 400x are likely not to be seen as quest rewards. `_a` will be for the icon repos that go the last mile `<pkmnid>.png` will be first fallback

Very well. This sounds good then.

**Review by whitewillem — APPROVED** [review]

**Comment by whitewillem** [comment]
With 7 votes in favour and none against... merged

**Pull request merged**
