### PR TITLE
add UIcons/scripts as submodule

### PR DESCRIPTION
**Pull request by whitewillem**

### CODE REVIEW

**Review by versx — APPROVED** [review]

**Review by nileplumb — APPROVED** [review]

**Comment by jepke** [comment]
Just throwing my idea out here.

If we make scripts folder within this repo, icon repos can include this repo in their repo as submodule that way they are always up to date with any changes made in the standard and always have up to date scripts available to them.

This will prevent different versions of scripts circulating which might cause faulty index files.

**Comment by whitewillem** [comment]
Submodules are not always up to date tho. The parent has to be updated every time

**Comment by jepke** [comment]
> Submodules are not always up to date tho. The parent has to be updated every time

If the dont pull locally true.

Icon users do not have a need to pull the submodules but i'd be easier for icon creators just to do a git pull local and run a script. `git config --global submodule.recurse true` is required to auto pull submodules.

Having a submodule in the iconrepo allows for a script that generates index.html that on its turn can be shown on github.io.
Submodule directly in the icon repo will give any script expected file paths.

**Comment by versx** [comment]
What's wrong with having them use `git pull --recurse-submodules`?

**Comment by whitewillem** [comment]
> What's wrong with having them use `git pull --recurse-submodules`?

Not wrong, but people might forget as most are not used to it. And that could result in faulty indexes when we change something later.

**Pull request closed without merging**
