### PR TITLE
add index.json

### PR DESCRIPTION
**Pull request by whitewillem**
Make it possible to propose changes to json/folder structure.

## Describe why this should be changed or added
Add a index.json to make it possible to propose changes to it.

## Describe alternatives you've considered
None :smile:

### CODE REVIEW

**Comment by whitewillem** [comment]
dont merge this just yet. should be more clear and prolly without all the file names

**Comment by jepke** [comment]
Beside mainlevel index.json i'd like to see every subfolder to have its own index.json too. This allows all projects to mix and match repositories or just use the pokemon folder for example. Mix and match will most likely mainly used in frontend applications to give users flexibility in which icons they want to use. But tools and bots can pick their subfolders directly.

**Comment by whitewillem** [comment]
Great idea but out of the scope of this pr. I will close it tho. We should add a tool to generate index.json instead.

**Comment by versx** [comment]
> Great idea but out of the scope of this pr. I will close it tho. We should add a tool to generate index.json instead.

Basic example to generate an index.json based on file names in current directory (although of course it'll need to be expanded):
Credits: https://github.com/Mygod/pokemon-icon-postprocessor
```
python -c "import os, json; print(json.dumps([os.path.splitext(file)[0] for file in os.listdir('.') if file.endswith('.png')], separators=(',', ':')))" > index.json
```

**Pull request closed without merging**
