### PR TITLE
Script proposal

### PR DESCRIPTION
**Pull request by jepke**
## Describe why this should be changed or added
Scripts folder creates a congregate location for scripts like index and preview generators. Github repository can be included as submodule in the icon repo so all updated scripts are always one command away for icon creators. At the same time icon repos have a link back here for guidelines in naming.

## Describe alternatives you've considered
I have not considered any.

## Additional context
I've added 2 placeholders in the scripts folder. Currently bash but this can be anything node python etc etc

### CODE REVIEW

**Comment by ccev** [comment]
Is it plausible to create complicated scripts like the preview generator in bash?

**Comment by ccev** [comment]
Also I know Nplumb uses Windows. Sh file can't run on windows right? So someone would have to write a script for Linux, Windows and possibly MacOS

**Comment by jepke** [comment]
> Is it plausible to create complicated scripts like the preview generator in bash?

Yes but my placeholders do not mean it needs to be bash. python and node will be more up to the task to create such a thing with a whole lot less lines of code. 

Bash will run on linux and macos native and it can be activated on win10.

**Comment by ccev** [comment]
Ok, since you mentioned the scripts should be in sh. I already have a preview generator working in Python.

**Comment by jepke** [comment]
> Ok, since you mentioned the scripts should be in sh. I already have a preview generator working in Python.

Where do i say it should be bash?

**Comment by ccev** [comment]
Last comment in #9

**Comment by jepke** [comment]
> Last comment in #9

>"Ideal script imo would be bash or a powershell script both natively run on Linux and windows. This will allow the icon creator to generate the json without the need to install anything like python node etc etc."

I said imo ideal would be bash or powershell. I've never said it should.

**Comment by versx** [comment]
> Also I know Nplumb uses Windows. Sh file can't run on windows right? So someone would have to write a script for Linux, Windows and possibly MacOS

Shell files can run just fine using WSL

**Pull request closed without merging**
